# Generated by Django 4.1.3 on 2022-11-21 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(15)])),
                ('phone_number', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('date', models.DateField(null=True)),
                ('time', models.CharField(choices=[('10am - 11am', '10am -11am'), ('11am - 12pm', '11am -12pm'), ('12pm - 1pm', '12pm -1pm'), ('1pm - 2pm', '1pm -2pm'), ('2pm - 3pm', '2pm -3pm'), ('3pm - 4pm', '3pm -4pm'), ('4pm - 5pm', '4pm -5pm'), ('5pm - 6pm', '5pm -6pm')], max_length=225, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
